### ISSUE TITLE
App breakage with unknown cover formats

### ISSUE THREAD

**Issue by dgcampea** [SoongNoonien/mpdevil#27] opened 2021-05-24 21:14 UTC
Found by trying to use "all artists".
Version: 1.2.1, flatpak
Log:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/mpdevil", line 2378, in render_covers
    album["cover"]=ClientHelper.binary_to_pixbuf(album["cover_binary"], size)
  File "/app/bin/mpdevil", line 506, in binary_to_pixbuf
    loader.write(binary)
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Unrecognized image file format (3)
```

**Comment by SoongNoonien** [comment] 2021-05-24 21:37
Hi!
This seems to be related to #14. In this case mpdevil tries to load the cover of some album with the readpicture/albumart command of mpd but GLib can't handle this image. Can you isolate the regarding album and send it to me, so I can work around this? But I sadly wont be able to get mpdevil displaying the cover correctly I can only ignore such images.

**Comment by dgcampea** [comment] 2021-05-24 21:45
> Can you isolate the regarding album and send it to me, so I can work around this? But I sadly wont be able to get mpdevil displaying the cover correctly I can only ignore such images.

Is there a way to enable some sort of verbose logging? I really have no idea which album is causing it as I stumbled upon this issue by pressing "all artists".

**Comment by SoongNoonien** [comment] 2021-05-24 21:55
> Is there a way to enable some sort of verbose logging?

No, not yet.

But you can go through each artists to isolate at least the artist. Isolating the album should than be relatively easy.

**Comment by SoongNoonien** [comment] 2021-05-24 22:01
Using 'log_level "verbose"' in the mpd.conf will show all issued mpd commands. This can also be very helpful since the album will be visible in there as a parameter of the "list" command and the regarding file as parameter of the "readpicture/albumart" command.

**Comment by dgcampea** [comment] 2021-05-25 00:23
I think I nailed it down. Blacklisting jpeg covers with `JFIF standard 1.02` fixes this. (Working jpeg files are `JFIF standard 1.01`).
```
$ file "cover.jpg"
cover.jpg: JPEG image data, JFIF standard 1.02 (...)
```

**Comment by SoongNoonien** [comment] 2021-05-25 15:17
This seems not to be the actual problem since I have many 1.02 files in my collection and they all work fine. Can you send me one of the covers that don't work, so I can reproduce this on my machine?

**Comment by dgcampea** [comment] 2021-05-25 15:21
I've sent a sample to the email address in git commits.

**Comment by SoongNoonien** [comment] 2021-06-01 16:32
Did you get my reply?

**Comment by dgcampea** [comment] 2021-06-01 20:23
Hi, yes, sorry I couldn't get back to you sooner, I'll let you know as soon as I can

**Comment by SoongNoonien** [comment] 2021-06-01 20:32
Ok, no problem. Take your time. I just wanted to know since your email curiously was in my spam folder.

**Comment by SoongNoonien** [comment] 2021-06-02 19:37
The newest commit fixes the issue on my machine. Please let my know if it is working on your machine too.

**Comment by dgcampea** [comment] 2021-06-02 20:52
I can confirm that it's working here as well (rebuilt flatpak to commit: 66bf9c310a046271b1fa84aab3387a91bc67cddb)

**Comment by SoongNoonien** [comment] 2021-06-02 21:03
Ok, so I'll close this.

**Closed by SoongNoonien** 2021-06-02 21:03 UTC

**Comment by dgcampea** [comment] 2021-06-02 21:45
Thanks for the speedy fix!
