### ISSUE TITLE
Frozen during startup

### ISSUE THREAD

**Issue by gerroon** [SoongNoonien/mpdevil#31] opened 2021-06-03 23:39 UTC
Hi

I installed this on Debian using Flatpak. When I run it is in frozen state while "connecting". I have bunch of Mpd servers running on the network and on the machine running Mpdevil, and it is running at default port 6600 with interface "any"

````

latpak run org.mpdevil.mpdevil



Traceback (most recent call last):
  File "/app/bin/mpdevil", line 2202, in _on_reconnected
    self._refresh()
  File "/app/bin/mpdevil", line 2116, in _refresh
    artists=self._client.comp_list(self._settings.get_artist_type())
  File "/app/bin/mpdevil", line 677, in comp_list
    native_list=self.list(*args)
  File "/app/lib/python3.8/site-packages/mpd/base.py", line 469, in mpd_command
    return wrapper(self, name, args, callback)
  File "/app/lib/python3.8/site-packages/mpd/base.py", line 532, in _execute
    return retval()
  File "/app/lib/python3.8/site-packages/mpd/base.py", line 457, in command_callback
    res = self._wrap_iterator(res)
  File "/app/lib/python3.8/site-packages/mpd/base.py", line 706, in _wrap_iterator
    return list(iterator)
  File "/app/lib/python3.8/site-packages/mpd/base.py", line 240, in _parse_objects
    for key, value in self._parse_pairs(lines):
  File "/app/lib/python3.8/site-packages/mpd/base.py", line 235, in _parse_pairs
    for line in lines:
  File "/app/lib/python3.8/site-packages/mpd/base.py", line 586, in _read_lines
    line = self._read_line()
  File "/app/lib/python3.8/site-packages/mpd/base.py", line 571, in _read_line
    raise ConnectionError("Connection lost while reading line")
mpd.base.ConnectionError: Connection lost while reading line
Traceback (most recent call last):
  File "/app/bin/mpdevil", line 1919, in _on_reconnected
    for tag in self._client.tagtypes():
  File "/app/lib/python3.8/site-packages/mpd/base.py", line 469, in mpd_command
    return wrapper(self, name, args, callback)
  File "/app/lib/python3.8/site-packages/mpd/base.py", line 530, in _execute
    self._write_command(command, args)
  File "/app/lib/python3.8/site-packages/mpd/base.py", line 565, in _write_command
    self._write_line(cmd)
  File "/app/lib/python3.8/site-packages/mpd/base.py", line 537, in _write_line
    self._wfile.write("{}\n".format(line))
  File "/app/lib/python3.8/site-packages/mpd/base.py", line 479, in _dummy
    raise ConnectionError("Not connected")
mpd.base.ConnectionError: Not connected



```



thanks

**Comment by SoongNoonien** [comment] 2021-06-04 09:12
Hi!
Hm, this seems weird... What do you mean by 'interface "any"'? Mpdevil freezes because it looses connection to the server while or perhaps even before fetching the available artist names. Please run the attached [code](https://github.com/SoongNoonien/mpdevil/files/6597189/test31.py.zip) inside the flatpak environment to see if this is reproducible with a small code snippet. You have to set the correct host though in line 2. Does mpdevil freeze every time you start it?

**Comment by Forage** [comment] 2021-06-04 13:08
If you say 'multiple servers' I get the feeling you are using a RPi as server. If this is the case make sure you are running at least MPD 0.22.6 (0.22.4 might be sufficient as well). MPD 0.22.3 is causing freezes in combination with a RPi (#26).

**Comment by SoongNoonien** [comment] 2021-06-04 14:14
I don't think this is the issue since in this case it seems to be frozen right away from start. Long before any cover is loaded. But using recent versions of MPD is always a preferable :)

**Comment by gerroon** [comment] 2021-06-04 16:31
I do not have rpis. None of my Mpd clients, including the local ones like ncmpcpp or any MPD Android clients have no issue connecting to this server or the rest of them. This is definetely Mpdevil related.

**Comment by SoongNoonien** [comment] 2021-06-04 17:34
> None of my Mpd clients, including the local ones like ncmpcpp or any MPD Android clients have issues connecting to this server or the rest of them.

Well, as I said mpdevil does find and connect to your server it just looses connection right after that when it is trying to load your artists.

> This is definetely Mpdevil related.

That's what I'm not sure about yet. Mpdevil uses python-mpd2 to talk to the MPD server, like other client written in python (e.g. Sonata) do too. With the result of the test code I want to see if it's me (mpdevil) running the wrong commands or if it's some kind of a bug in python-mpd2.

> I meant that MPD listens on any interface, so any local (on the pc that is running Mpdevil) should be able to find the running MPD, which other clients can find easily. MPD and Mpdevil are running on the same pc.

Ok, thanks now I see. :) Than the test code should run without any modifications.

> How do I run the code inside a Flatpak environment? Not sure what Flatpak environment means in this context.
I mean the environment in which you run the mpdevil command. The only problem is to get the code available from inside the flatpak. Mpdevil has access to the xdg music folder in your home per default. On my machine this is `~/Musik` on an English installation the default would be `~/Music`. So one solution to run the code inside the flatpak environment would be:
- extract the .zip file with the code inside
- place the code inside your music folder (xdg music folder)
- Open a new terminal and run commands like this:
```
[martin@localhost ~]$ flatpak run --command=sh org.mpdevil.mpdevil
[📦 org.mpdevil.mpdevil ~]$ ls
Musik
[📦 org.mpdevil.mpdevil ~]$ cd Musik/
[📦 org.mpdevil.mpdevil Musik]$ python test31.py 
81
317
0.22.4
{'uptime': '34883', 'playtime': '0', 'artists': '316', 'albums': '413', 'songs': '5127', 'db_playtime': '1441436', 'db_update': '1622637090'}
[📦 org.mpdevil.mpdevil Musik]$ 
```
The name "Musik" probably is different on your machine. :)

**Comment by gerroon** [comment] 2021-06-05 23:00
```
[📦 org.mpdevil.mpdevil MEDIA]$ python3 test31.py 
6063
13565
0.22.4
{'uptime': '371362', 'playtime': '29578', 'artists': 'XXXXX', 'albums': 'XXXX', 'songs': 'XXXXX', 'db_playtime': '36374682', 'db_update': '1622927876'}

```

**Comment by SoongNoonien** [comment] 2021-06-06 07:57
Ok, so the connection apparently is lost right before mpdevil fetches the artists. To verify this suspicion please run in the same way this [code](https://github.com/SoongNoonien/mpdevil/files/6603815/test31-a.py.zip). The last MPD related command which is run before the artists get loaded in line 2202->2116->677 (where the original error occurs) is a command which fetches all the genres so I added this one to the test code.

**Comment by gerroon** [comment] 2021-06-06 17:15
📦 org.mpdevil.mpdevil MEDIA]$ python3 test31-a.py 
1149
6063
13565
0.22.4

**Comment by SoongNoonien** [comment] 2021-06-06 19:58
> I do not want people to know how may artists or songs I have here.

Yes, no problem. The purpose of the test was to see if it is working not how many artists you have.

But sadly this did not have the desired effect. I'm afraid I can't tell where the issue is right now. Do you have any special settings in the mpd.conf (if possible send me the config)? Did mpdevil ever start on your machine? Since I can't reproduce it, it's very hard for me to find the error. Currently I can only see that mpdevil connects successfully and looses the connection for an unknown reason.

**Comment by SoongNoonien** [comment] 2021-06-06 20:10
I don't know if this is possible for you but adding
```
import logging
logging.basicConfig(level=logging.DEBUG)
```
right after `#!/usr/bin/python3` in the `/bin/mpdevil` file would give some information about what MPD commands are issued before the error occurs. Also the verbose MPD log would be helpful.

**Comment by 3291823** [comment] 2021-06-13 14:23
I am having the exact same issue. Stuck on 'connecting'.
` ~ > mpdevil

INFO:mpd.base:Calling MPD connect('localhost', 6600, timeout=None)
DEBUG:mpd.base:Calling MPD commands()
DEBUG:mpd.base:Calling MPD ping()
DEBUG:mpd.base:Calling MPD ping()
DEBUG:mpd.base:Calling MPD ping()
DEBUG:mpd.base:Calling MPD list('genre',)
zsh: killed     mpdevil`

**Comment by SoongNoonien** [comment] 2021-06-13 19:22
Hi!
Ok, it's good to have another one with the same issue. It's very hard to make a good analysis without the ability to reproduce the bug but I'll do my best. Something is happening between fetching the genres and fetching the artists which leads to a connection loss. Since issuing both of these commands in a script right after the other doesn't trigger the bug it has to be something mpdevil is doing. My current theory is that mpdevil tries to display the genres and this takes (for whatever reason) to long so the MPD server closes the connection due to timeout exceeding.
So to verify this I created a test branch named "bug31" which skips the displaying of the genres. Please try it and send me the output on the console.

**Comment by gerroon** [comment] 2021-06-13 19:46
My MPD media/music files are on a Samba drive if it helps.

**Comment by SoongNoonien** [comment] 2021-06-13 20:36
I was not able to reproduce the issue with a Samaba server.

**Comment by SoongNoonien** [comment] 2021-06-14 06:50
@gerroon Did you try the "bug31" branch? This would help even more.

**Comment by gerroon** [comment] 2021-06-14 15:29
No I have not since I was using the flathub version. Let me see how I can install it.

**Comment by SoongNoonien** [comment] 2021-06-14 15:38
I try to build a flatpak from that branch.

**Comment by SoongNoonien** [comment] 2021-06-14 16:00
Download and extract this [archive](https://github.com/SoongNoonien/mpdevil/files/6649668/bug31.zip). Execute `flatpak-builder --run build/ org.mpdevil.mpdevil.json mpdevil` in the directory "bug31" to start the patched mpdevil version.

**Comment by gerroon** [comment] 2021-06-14 17:36
I am getting `error: runtime/org.gnome.Sdk/x86_64/3.38 not installed` Not sure how I can install this with flatpak

**Comment by SoongNoonien** [comment] 2021-06-14 17:45
The test runs in flatpak user context. You probably installed mpdevil in the system context so the dependencies are not found. Just run `flatpak --user install runtime/org.gnome.Sdk/x86_64/3.38` as normal user.

**Comment by SoongNoonien** [comment] 2021-06-15 10:35
If the package still cannot be found you may have to add the flathub repo in user context. At least this is what was needed on my fedora test machine. `flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

**Comment by gerroon** [comment] 2021-06-15 16:41
I was finally able to install it  with the line you posted above.

This version seems to opens fine, although there is still abit of delay but nothing like the release version. It seems to be due to the scaning goes in the bg. I have many thousands of media files.

**Comment by SoongNoonien** [comment] 2021-06-15 17:35
Nice!

> ...although there is still abit of delay but nothing like the release version

With my Samba test I also noticed a delay. But after a while of testing it was gone. My collection has about 5000 songs so it probably is way smaller than yours.

So we were able to narrow it down a bit further. The problem is that displaying your genres takes to long. This is the only thing changed in the code. I don't think it is due to the number of genres. This may be an encoding/tag issue which makes trouble with gtk. To fix this I either need a complete list of your genres to reproduce the issue on my machine or you try to isolate one file which causes the issue. If you don't want to post your genres here you can send them to me in a private mail. But it is really imported to not change the encoding, the best way to send it as a mail would be in a separate text file attached to the mail. 
If you know a better solution to find the bug form here please let me know.

**Comment by 3291823** [comment] 2021-06-16 12:18
Bug31 branch works, everything loads & functions as expected.
```
 ~/dl/git/mpdevil/bin > ./mpdevil
INFO:mpd.base:Calling MPD connect('localhost', 6600, timeout=None)
DEBUG:mpd.base:Calling MPD commands()
DEBUG:mpd.base:Calling MPD ping()
DEBUG:mpd.base:Calling MPD ping()
DEBUG:mpd.base:Calling MPD ping()
omit genres
DEBUG:mpd.base:Calling MPD list('albumartist',)
DEBUG:mpd.base:Calling MPD currentsong()
DEBUG:mpd.base:Calling MPD list('album', 'albumartist', 'メディカル')
DEBUG:mpd.base:Calling MPD list('date', 'album', 'Underdose', 'albumartist', 'メディカル')
DEBUG:mpd.base:Calling MPD find('album', 'Underdose', 'date', '2019', 'albumartist', 'メディカル')
```
```
 ~ > mpc list genre | wc -l
2038
```

Takes a little while to click thru artists to load the index/album art,  but it functions. 
```
 ~ > mpc stats
Artists:   9682
Albums:    7557
Songs:    83025

DB Updated:   Sun Jun 13 17:38:33 2021
DB Play Time: 264 days, 13:29:31
```

I suppose that solves the issue.  Thanks.

**Comment by SoongNoonien** [comment] 2021-06-16 12:33
> Bug31 branch works, everything loads & functions as expected.

Ok, that's good.

> I suppose that solves the issue. Thanks.

Sadly not since the genre filter in the top left corner is not usable with that branch.

**Comment by SoongNoonien** [comment] 2021-06-19 07:26
Hi!
I did another small test on my machine. I just filled the genre filter with 1000 dummy values. This reproduced the issue! So it is definitely caused by the number of genres. I don't know if you are interested in the details but I use a GtkComboBoxText to display the genres and this issue could be related to https://gitlab.gnome.org/GNOME/gtk/-/issues/1910. I'll try to dig deeper and find a solution. So I don't need a list of your genres anymore.

Thanks for your effort on helping to find the issue!

**Comment by SoongNoonien** [comment] 2021-06-24 19:45
Hi!
This should now be fixed in master. I reworked the genre filter and made some minor speed improvements. This should decrease the delays related to large collections you mentioned. Please take a look. [This](https://github.com/SoongNoonien/mpdevil/files/6711756/master.zip) is a flatpak containing the regarding commit similar to the last one.

**Comment by SoongNoonien** [comment] 2021-07-19 19:54
Ok, I consider this solved now.

**Closed by SoongNoonien** 2021-07-19 19:54 UTC
Labels: bug
