### ISSUE TITLE
Show button not working

### ISSUE THREAD

**Issue by brolyxxx** [SoongNoonien/mpdevil#72] opened 2023-02-01 21:33 UTC
- Arch Linux 6.1.8-arch1-1
- mpdevil installed from [AUR](https://aur.archlinux.org/packages/mpdevil-git) (git version)
- version: 1.10.1.r0.g97e6a37-1

The **Show** button in the context menu doesn't work as intended, nothing happens and the console returns the following error:
```
Traceback (most recent call last):
  File "/usr/bin/mpdevil", line 1335, in <lambda>
    self._show_action.connect("activate", lambda *args: self._client.show_in_file_manager(self._store[self.get_cursor()[0]][3]))
  File "/usr/bin/mpdevil", line 877, in show_in_file_manager
    proxy.call_sync("ShowItems", GLib.Variant("(ass)", ((file.get_uri(),),"")), Gio.DBusCallFlags.NONE, 500, None)
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.FileManager1 was not provided by any .service files (2)
```

![image](https://user-images.githubusercontent.com/8193498/216167685-14feb2bc-7bc9-459c-b130-1625d2ae177b.png)

Thanks for helping!

**Comment by brolyxxx** [comment] 2023-02-05 23:17
You're right, the only graphical file manager installed is PCManFM and I don't think it uses dbus (at least I don't see it among the dependencies.

**Comment by SoongNoonien** [comment] 2023-02-26 10:56
I finally got the time to work on this. The newest commit tests if `org.freedesktop.FileManager1` is available. Can you verify that the show button is now inactive on your setup?

**Comment by brolyxxx** [comment] 2023-03-01 13:08
Yep, confirmed: the Show button is now greyed out. Thanks for the fix, ok for me to close the issue.

**Comment by SoongNoonien** [comment] 2023-03-01 13:59
Ok, good.

As far as I can tell the gtk branch of pcmanfm is pretty much dead alongside lxde. So if you are interested in this feature you could try pcmanfm-qt (https://github.com/lxqt/pcmanfm-qt/issues/1194) if the toolkit is not relevant to you. Of course the file managers of most of the various DEs also support this feature.

**Comment by linnabraham** [comment] 2024-02-07 06:25
The show button is still greyed out for me.  I am using pcmanfm-qt which I believe has already included support for the feature being mentioned. Opening file location through the browser window works as well for brave. 

Thus I guess this issue has something to do with my mpdevil installation. 
I am on arch linux and have tried both the latest versions of mpdevil and mpdevil-git versions.

**Comment by linnabraham** [comment] 2024-02-08 07:32
I guess,  using service. I checked the status of systemctl --user status {mpd.service, mpd.socket} and only mpd.service seems to be up and running. 

However I did find this line in the logs 
Feb 08 09:42:06 archlinux mpd[544]: server_socket: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use

**Comment by SoongNoonien** [comment] 2024-02-08 14:35
No, this not what I meant. How did you configure mpdevil to connect to your server? If you're unsure you can just send a screenshot of the respective part of the settings window.

**Comment by linnabraham** [comment] 2024-02-08 16:13
Okay. That is not socket. Through network itself.  Attaching the picture as well.
![pic-selected-240208-2142-41](https://github.com/SoongNoonien/mpdevil/assets/26475236/36c42bab-68f6-4877-a422-cb24b513e850)

**Comment by linnabraham** [comment] 2024-02-09 12:18
That doesn't happen despite changing that to my mpd directory. Do I need to do anything else apart from inserting the proper directory path in the field? Do I need to enable the socket checkbox or press connect? I pressed the OK button and rebooted still nothing happens.

**Comment by SoongNoonien** [comment] 2024-02-09 21:21
> Do I need to do anything else apart from inserting the proper directory path in the field?

No, this is everything needed to find the files on your disk.

> Do I need to enable the socket checkbox or press connect?

No, but this way you don't need to specify the path to your music.

> I pressed the OK button and rebooted still nothing happens.

If the "show" button is still inactive then your file manager seems to be incompatible.

**Comment by linnabraham** [comment] 2024-02-11 05:00
Can you help me troubleshoot this? Coz I am using pcmanfm-qt as per the discussion in this thread which seems to have implemented the feature. I also find that there are no issues with other apps that I use like Brave, Zotero etc.

**Comment by SoongNoonien** [comment] 2024-02-11 10:09
> Can you help me troubleshoot this?

I can try but I need some information about your setup. I just tested openbox with pcmanfm-qt and it works just fine. Do you start pcmanfm when you log in? Otherwise it can't provide the dbus service. I simply added `pcmanfm-qt --desktop &` to `~/.config/openbox/autostart`. Take a look at https://wiki.archlinux.org/title/PCManFM for reference (Note that all appearances of `pcmanfm` in the command line examples need to be replaced with `pcmanfm-qt`).

> I also find that there are no issues with other apps that I use like Brave, Zotero etc.

Probably all of them have several fallbacks to support every possible system.

**Comment by linnabraham** [comment] 2024-02-12 04:19
> I can try but I need some information about your setup. I just tested openbox with pcmanfm-qt and it works just fine.

This is surprising. Until recently I was using openbox. I have now switched to i3-gaps. The issue was present while I was on openbox and I can confirm it is still there since I temporarily switched to openbox and saw that button is greyed out.

> Do you start pcmanfm when you log in? Otherwise it can't provide the dbus service. I simply added pcmanfm-qt --desktop & to ~/.config/openbox/autostart. Take a look at https://wiki.archlinux.org/title/PCManFM for reference (Note that all appearances of pcmanfm in the command line examples need to be replaced with pcmanfm-qt).

I had come across these pages, currently I'm using the `pcmanfm-qt --daemon-mode &` in my autostart since the other command changes my wallpaper and does lot of other stuff, I thought this must be the command that provides the dbus interface. However I changed that with command you gave and rebooted into openbox and still doesn't work.

Regarding my current setup what more details could be useful for troubleshooting. I have a pretty basic i3-gaps config file at the end of which I use `exec` to source the same openbox autostart file I was previously using. Commenting out any lines I dont need in i3.

**Comment by SoongNoonien** [comment] 2024-02-12 10:00
> I had come across these pages, currently I'm using the pcmanfm-qt --daemon-mode & in my autostart...

Over here this is still enough.

> However I changed that with command you gave and rebooted into openbox and still doesn't work.

The only thing I see that could be wrong then is the configuration of the music directory. Maybe try to use the socket, this way the music directory is determined automatically.

**Comment by linnabraham** [comment] 2024-02-13 02:34
Ok I can confirm that despite having  `pcmanfm-qt --daemon-mode &` in my autostart and connecting to mpd via socket the problem still remains. 

Could the fact that I am using BTRFS partitioning have anything to do with it?

**Comment by SoongNoonien** [comment] 2024-02-13 13:37
> Ok I can confirm that despite having pcmanfm-qt --daemon-mode & in my autostart and connecting to mpd via socket the problem still remains.

Are there any errors on the console when your run mpdevil from there?

> Could the fact that I am using BTRFS partitioning have anything to do with it?

No, this shouldn't have any influence.

**Comment by linnabraham** [comment] 2024-02-14 09:14
> Are there any errors on the console when your run mpdevil from there?

Nothing. I actually I don't see any logs at all.

I just quickly set up mpd and mpdevil (v 1.10.2) on another Arch machine  with Openbox  that I had access to. The show button is still greyed out. 
Another thing that I checked is if the default filemanager is what we think it is. So I ran the command `xdg-mime query default inode/directory` to confirm that it is pcmanfm-qt. I am confused how you could get it to work on your set up.

**Comment by SoongNoonien** [comment] 2024-02-14 16:12
> I just quickly set up mpd and mpdevil (v 1.10.2) on another Arch machine with Openbox that I had access to. The show button is still greyed out.

If you're testing older versions you could also test 1.10.1 which was released prior to this bug report. In this version the show button is active even if the dbus interface is not available. But if it is still inactive there mpdevil simply can't find your files.

> Another thing that I checked is if the default filemanager is what we think it is. So I ran the command xdg-mime query default inode/directory to confirm that it is pcmanfm-qt.

This has absolutely nothing to do with the issue. You could very well set one file manager as default while a completely different one provides the dbus interface.

I think we are kind of stuck here. I'll set up a test branch in this repo with specific debug output to see why the button is inactive.

**Comment by SoongNoonien** [comment] 2024-02-14 18:33
> I'll set up a test branch in this repo with specific debug output to see why the button is inactive.

There is now a `dbus` branch. This is a direct link https://github.com/SoongNoonien/mpdevil/archive/refs/heads/dbus.zip. Please let me know which messages are printed to the console when you open a context menu with the inactive show button while using the modified version.

**Comment by linnabraham** [comment] 2024-02-15 04:57
```
dbus error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable (2)
```

This is the error I get.

**Comment by SoongNoonien** [comment] 2024-02-15 17:45
Ok, good. I think it is fixed now in master. I was able to reproduce it with this extra information.  The problem is that the dbus interface implementation of pcmanfm-qt apparently slightly differs from the implementation found in nautilus or dolphin.
In all my previous tests nautilus which was installed in parallel responded to the test for the dbus interface while pcmanfm-qt responded to the actual activation. The newset commit in master now tests for both possible implementations.
Please let me know if it is working over on your machines now as well.

**Comment by linnabraham** [comment] 2024-02-15 18:55
Hey...Yes. It works perfect now. Thanks for the long back and forth. Glad it's fixed. Had this issue for sometime now but not seeing any logs made me think it was something at my end. May I ask why the debug is not enabled by default?

**Comment by SoongNoonien** [comment] 2024-02-15 22:03
> It works perfect now.

Ok, nice.

> May I ask why the debug is not enabled by default?

I don't what the program to spam debug information on the console. I think a good program only prints something when an error occurs. But it is true that I could or maybe should improve the debug mode.

**Closed by SoongNoonien** 2024-02-15 22:03 UTC
