### ISSUE TITLE
cannot import name 'base' error

### ISSUE THREAD

**Issue by mgarbvs** [SoongNoonien/mpdevil#25] opened 2021-05-15 00:42 UTC
pi@raspberrypi:~ $ mpdevil
`Traceback (most recent call last):
  File "/usr/bin/mpdevil", line 24, in <module>
    from mpd import MPDClient, base as MPDBase
ImportError: cannot import name 'base'`

From installing on rpi. I have python3-mpd and python-mpd2 installed

**Comment by SoongNoonien** [comment] 2021-05-15 07:54
Hi,
I'm not completely familiar with the Debian package names but as far as I know they don't have a package named `python-mpd2`, was this installed via pip? `python3-mpd` should already be sufficient (this is the package I use as dependency for the .deb package). What is the version of `python3-mpd` and how did you install `mpdevil`? Even when no dependencies are installed it is sufficient to install my .deb package and leave the dependency resolution to dpkg.

**Comment by SoongNoonien** [comment] 2021-06-13 19:26
It's been almost an entire month since your bug report. If you still want to solve this let me know. But I think it's not a bug in the software itself but an installation problem. So I'll close this for now.

**Closed by SoongNoonien** 2021-06-13 19:26 UTC
Labels: waiting
